# Generated by Django 4.2.11 on 2024-03-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='Problems', to='maths.category'),
        ),
    ]
